trigger:
    branches:
        include:
            - main
pr: none

# schedules:
#     - cron: "0 9 * * Mon-Thu"
#       displayName: Nightly Release Schedule
#       branches:
#           include:
#               - main

resources:
    repositories:
        - repository: templates
          type: github
          name: microsoft/vscode-engineering
          ref: main
          endpoint: Monaco

parameters:
    - name: publishExtension
      displayName: 🚀 Publish Extension
      type: boolean
      default: false

extends:
    template: azure-pipelines/extension/pre-release.yml@templates
    parameters:
        publishExtension: ${{ parameters.publishExtension }}
        workingDirectory: $(Build.SourcesDirectory)/vscode-extension
        vscePackageArgs: --yarn
        ghCreateTag: true

        buildSteps:
            - script: yarn install --frozen-lockfile
              displayName: Install dependencies

            - script: yarn run patch-prerelease $(Build.BuildNumber)
              displayName: Apply prerelease patch
              workingDirectory: $(Build.SourcesDirectory)/vscode-extension

            - script: yarn run build
              displayName: Build

            - script: yarn run test
              displayName: Test

        tsa:
            config:
                areaPath: "Visual Studio Code Miscellaneous Extensions"
                serviceTreeID: "c8cb03c6-176e-40dd-90a5-518de08666dc"
            enabled: true
